config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "medicals#index"
  resources :users, only: [:edit, :update]
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :medicals, only: [:new, :create] do
    resources :exams
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :user
  belongs_to :medical
  has_one_attached :image

  with_options if: :was_attached? do
    validates :title, presence: true
    validates :hospital, presence: true
    validates :exam_date, presence: true
    validates :comment, presence: true
  end

  def was_attached?
    self.image.attached?
  end
end

app/models/medical.rb
class Medical < ApplicationRecord
  belongs_to :user
  has_many :exams

  validates :subject, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :name
    validates :birthday
  end

  has_many :medicals
  has_many :exams
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :birthday])
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_medical

  def index
    @exams = @medical.exams.includes(:user).order("exam_date DESC")
  end

  def new
    @exam = Exam.new
  end
  
  def create
    @exam = @medical.exams.new(exam_params)
    if @exam.save
      redirect_to medical_exams_path(@medical), notice: 'Record was successfully created.'
    else
      @exams = @medical.exams.includes(:user)
      render :new, status: :unprocessable_entity
      # バリデーションエラー出力
    end
  end

  def show
    @exam = @medical.exams.find(params[:id])
  end

  private

  def set_medical
    @medical = Medical.find(params[:medical_id])
  end

  def exam_params
    params.require(:exam).permit(:image, :title, :hospital, :exam_date, :comment).merge(user_id: current_user.id)
  end

end

app/controllers/medicals_controller.rb
class MedicalsController < ApplicationController
  def new
    @medical = Medical.new
  end

  def create
    @medical = Medical.new(medical_params)
    if @medical.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
      # バリデーションエラー出力
    end
  end

  private

  def medical_params
    params.require(:medical).permit(:subject).merge(user_id: current_user.id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :birthday)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/exams/_exam.html.erb
<div class="entry">
  <div class="upper-entry">
    <div class="entry-title">
      <%= link_to exam.title ,medical_exam_path(@medical,exam) %>
    </div>
    <div class="entry-date">
      <%= exam.exam_date %>
    </div>
  </div>

  <div class="lower-entry">
    <div class="entry-hospital">
      <%= exam.hospital %>
    </div>
  </div>
</div>

app/views/exams/_main_entry.html.erb
<div class="main-header">
  <div class="left-header">
    <div class="header-title">
      <%= @medical.subject %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-btn">
      <%= link_to "記録", new_medical_exam_path(@medical) %>
    </div>
  </div>
</div>

<div class="entries">
  <%= render partial: 'exam', collection: @exams %>
</div>

app/views/exams/_side_bar.html.erb
<div class="side-bar-header">
  <div class="app-name">
    MY カルテ
  </div>
  <div class="user-nav">
    <span><%= current_user.name %>
      <ul class="user__info">
        <li>
          <%= link_to "アカウント編集", edit_user_path(current_user)  %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    </span>
  </div>
</div>

<div class="subjects">
  <div class="create-note">
    <%= link_to "ノート作成", new_medical_path %>
  </div>

  <div class="notes">
    <% current_user.medicals.each do |medical| %>
      <div class="note">
        <div class="subject-name">
          <%= link_to medical.subject, medical_exams_path(medical) %>
        </div>
      </div>
    <% end %>
    
  </div>
</div>

app/views/exams/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  
  <div class="main">
    <%= render "main_entry" %>
  </div>
</div>

app/views/exams/new.html.erb
<div class='exam-form'>
  <h3>新規診療記録</h3>

    <%= form_with model: [@medical, @exam], local: true do |f| %>

    <%= render "devise/shared/error_messages", model: f.object %>

    <div class='exam-form__field'>
      <div class='exam-form__field--left'>
        <%= f.label :hospital, :病院名, class: 'exam-form__label' %>
      </div>
      <div class='exam-form__field--right'>
        <%= f.text_field :hospital, class: 'exam-form__input', placeholder: '受診した病院名' %>
      </div>

      <div class='exam-form__field--left'>
        <%= f.label :exam_date, :診察日, class: 'exam-form__label' %>
      </div>
      <div class='exam-form__field--right'>
        <%= f.date_field :exam_date, class: 'exam-form__input-date' %> 
      </div>

      <div class='exam-form__field--left'>
        <%= f.label :title, :タイトル, class: 'exam-form__label' %>
      </div>
      <div class='exam-form__field--right'>
        <%= f.text_field :title, class: 'exam-form__input', placeholder: '記録のタイトル' %>
      </div>

      <div class='exam-form__field--left'>
        <%= f.label :comment, :コメント, class: 'exam-form__label' %>
      </div>
      <div class='exam-form__field--right'>
        <%= f.text_area :comment, class: 'exam-form__input', placeholder: '受診の経緯、結果、所見等', rows: '10' %>
      </div>

      <div class='exam-form__field--left'>
        <%= f.label :image, :画像, class: 'exam-form__label-image' %>
      </div>
      <div class='exam-form__field--right'>
        <%= f.file_field :image, class: 'exam-form__image' %>
      </div>

      <div class='exam-form__field--left'>
      </div>
      <div class='exam-form__field--right'>
        <%= f.submit '保存', class: 'exam-form__action-btn' %>
      </div>

    </div>
    <% end %>
</div>

app/views/exams/show.html.erb
<div class="exam-show">
  <div class="show-head">
    <div class="show-head_left">
      <h3><%= @exam.title %></h3>
    </div>
    <div class="show-head_right">
      <div class="show-edit_btn">
        <a> 編集</a>
      </div>
      <div class="show-destroy">
        <a>削除</a>
      </div>
    </div>
  </div>

  <div class="show-box">
    <div class="img-box">
      <div class="exam-img">
        <%= image_tag @exam.image if @exam.image.attached? %>
      </div>
    </div>

    <div class="show-explain-box">
      <div class="detail-hos"><%= @exam.hospital %></div>
      <div class="detail-date">
        <div class="show-date"><%= @exam.exam_date %></div>
        <div class="date-cal">
          
        </div>
      </div>
      <div class="detail-comment"><%= @exam.comment %></div>
    </div>
  </div>

  <div class="show-foot">
    <div class="back-btn">
      <a>戻る</a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyKarte</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/medicals/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "exams/side_bar" %>
  </div>
</div>

app/views/medicals/new.html.erb
<div class='chat-room-form'>
  <h1>新規診療ノート作成</h1>
  <%=form_with model: @medical, local: true do |f|%>

  <%= render "devise/shared/error_messages", model: f.object %>

    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :subject, :診療科名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :subject, class: 'chat__room_name chat-room-form__input', placeholder: '診療科名を入力してください'%>
      </div>
    </div>

    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit '保存', class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>アカウントの編集</h2>
      <%= link_to "トップページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :名前%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :メールアドレス%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label :生年月日%>
          </div>
          <div class='field-input-birth'>
            <%= raw sprintf(
              f.date_select(
                :birthday,
                class:'select-birth',
                id:"birth-date",
                use_month_numbers: true,
                prompt:'--',
                start_year: 1930,
                end_year: (Time.now.year),
                date_separator: '%s'),
              "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
          </div>
        </div>

        <div class='actions'>
          <%= f.submit "更新", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>